### ISSUE TITLE
Alternatives after 2 years?

### ISSUE THREAD

**Issue by dselivanov** [alexfun/rserve-surf-public#1]
Thank you very much for sharing. `Rserve` and `FastRWeb` are really awesome applications, but documentation is sparse (and not that many people share their experience). 
I'm researching about how to convert my R application into high-performance web microservice with REST API. `Rserve` look like very solid solution (but still not sure how to combine it with some http server. now looking into`FastRWeb`). 
Do you know any better alternatives? (mb something changed after 2 years).
Thanks.

**Comment by alexfun** [comment]
Thanks for getting in touch. I have not really used R server side since I wrote this, however I am not aware of any other developments which let you replicate what FastRWeb has done, except possibly using some integration with Microsoft's Azure.

Back when I was using it, I did not find that it had any shortcomings. I wish I had time to explore supporting https, which I believe is supported but I did not test. But I am not a web developer so I do not know what other features one might want from an API service. In addition, it was able to multithread processes very well on my server, but it would be interesting to know whether you can add something like Amazon's elastic beanstalk on it to support variable loads.

If I may ask, how did you find this page?

**Comment by dselivanov** [comment]
I googled something about `Rserve` + `FastRWeb` and found meetup page with link to this repo. I'm not web developer as well. Couple of years ago I tried `RServe` with Java client (so all http related logic was on java side). And I was really impressed by low latency, scalability with number of cores and stability of Rserve.
Quite similar approach is used by [Domino Data Lab](http://blog.revolutionanalytics.com/2014/08/using-r-inside-the-enterprise-integration-with-existing-systems.html).

There are some less performant solutions like [plumber](https://github.com/trestletech/plumber) or [opencpu](https://www.opencpu.org/). 
And here is [CRAN WebTechnologies task view](https://cran.r-project.org/web/views/WebTechnologies.html) which I found up to date and quite useful.

**Comment by dselivanov** [comment]
Once more thanks for sharing. Closing this issue.

**Comment by alexfun** [comment]
If you have some time, I would be keen to hear your thoughts on this article which mentions plumber and compares in to Rserve:

http://jaehyeon-kim.github.io/2017/11/API-Development-with-R-Part-I.html

**Comment by dselivanov** [comment]
@alexfun FYI I've developed  https://github.com/dselivanov/RestRserve.

**Comment by alexfun** [comment]
Ah, looks interesting thanks. I have a chance to meet Jaehyeon (from above link). If I do I will let him know of your development.
